# Digimon World 2003, Europe (SLES-03936): soundtst
name: soundtst
sha1: c755a4a080b086bcc8c6020c46034fd17d7cbebc
options:
  basename: soundtst
  target_path: disks/eu/AAA/PRO/SOUNDTST.PRO
  base_path: ../..
  platform: psx
  compiler: GCC

  asm_path: asm/eu/soundtst
  src_path: src/soundtst
  build_path: build/eu

  ld_script_path: build/eu/generated/soundtst.ld

  global_vram_start: 0x80000000
  global_vram_end: 0x80200000

  find_file_boundaries: True
  gp_value: 0x8005CB50

  generate_asm_macros_files: False

  section_order: [".rodata", ".text", ".data", ".bss"]

  symbol_addrs_path:
    - config/eu/symbols.txt
    - config/eu/symbols_soundtst.txt

  undefined_funcs_auto_path: build/eu/generated/undefined_funcs_auto_soundtst.txt
  undefined_syms_auto_path: build/eu/generated/undefined_syms_auto_soundtst.txt

  string_encoding: ASCII
  data_string_encoding: ASCII
  rodata_string_guesser_level: 2
  data_string_guesser_level: 2

  ld_bss_is_noload: False

  migrate_rodata_to_functions: True
  create_data_pads: False

segments:
  # not split into the USA version's files yet: its rodata, code and data
  - name: soundtst
    type: code
    start: 0x0
    vram: 0x80082CB0
    align: 4
    subalign: 4
    subsegments:
      - [0x0, rodata, soundtst]
      - [0x16C0, asm, soundtst]
      - [0x20C4, data, soundtst]
  - [0x2D98]
