# Digimon World 2003, Europe (SLES-03936): stcrddek
name: stcrddek
sha1: f813f89a1ab17597e6a429c42d0acd81dd41aa49
options:
  basename: stcrddek
  target_path: disks/eu/AAA/PRO/STCRDDEK.PRO
  base_path: ../..
  platform: psx
  compiler: GCC

  asm_path: asm/eu/stcrddek
  asset_path: asm/eu/stcrddek/bin
  src_path: src/stcrddek
  build_path: build/eu

  ld_script_path: build/eu/generated/stcrddek.ld

  symbol_addrs_path:
    - config/eu/symbols.txt
  undefined_funcs_auto_path: build/eu/generated/undefined_funcs_auto_stcrddek.txt
  undefined_syms_auto_path: build/eu/generated/undefined_syms_auto_stcrddek.txt

  generate_asm_macros_files: False
  create_c_files: False

segments:
  # still one blob, not split into the USA version's files yet
  - name: stcrddek
    type: databin
    start: 0x0
    vram: 0x80082CB0
    subalign: 4

  - [0x8BA4]
