# Digimon World 2003, Europe (SLES-03936): stcrdabm
name: stcrdabm
sha1: 0e58e7aef70165be0bb6b95d59236941ab648b28
options:
  basename: stcrdabm
  target_path: disks/eu/AAA/PRO/STCRDABM.PRO
  base_path: ../..
  platform: psx
  compiler: GCC

  asm_path: asm/eu/stcrdabm
  src_path: src/stcrdabm
  build_path: build/eu

  ld_script_path: build/eu/generated/stcrdabm.ld

  global_vram_start: 0x80000000
  global_vram_end: 0x80200000

  find_file_boundaries: True
  gp_value: 0x8005CB50

  generate_asm_macros_files: False

  section_order: [".rodata", ".text", ".data", ".bss"]

  symbol_addrs_path:
    - config/eu/symbols.txt
    - config/eu/symbols_stcrdabm.txt

  undefined_funcs_auto_path: build/eu/generated/undefined_funcs_auto_stcrdabm.txt
  undefined_syms_auto_path: build/eu/generated/undefined_syms_auto_stcrdabm.txt

  string_encoding: ASCII
  data_string_encoding: ASCII
  rodata_string_guesser_level: 2
  data_string_guesser_level: 2

  ld_bss_is_noload: False

  migrate_rodata_to_functions: True
  create_data_pads: False

segments:
  - name: stcrdabm
    type: code
    start: 0x0
    vram: 0x80082CB0
    align: 4
    subalign: 4
    subsegments:
      # us's modules, each with its rodata, data and bss (tools/split_version.py)
      - [0x0, rodata, stcrdabm]
      - [0xD8, asm, stcrdabm]
      - [0x2D9C, data, stcrdabm]
  - [0x2DCC]
