# Digimon World 2003, Europe (SLES-03936): stcrdshp
name: stcrdshp
sha1: d1e01bd598694a6aa8ddd0978f6d382fa970d314
options:
  basename: stcrdshp
  target_path: disks/eu/AAA/PRO/STCRDSHP.PRO
  base_path: ../..
  platform: psx
  compiler: GCC

  asm_path: asm/eu/stcrdshp
  asset_path: asm/eu/stcrdshp/bin
  src_path: src/stcrdshp
  build_path: build/eu

  ld_script_path: build/eu/generated/stcrdshp.ld

  symbol_addrs_path:
    - config/eu/symbols.txt
  undefined_funcs_auto_path: build/eu/generated/undefined_funcs_auto_stcrdshp.txt
  undefined_syms_auto_path: build/eu/generated/undefined_syms_auto_stcrdshp.txt

  generate_asm_macros_files: False
  create_c_files: False

segments:
  # still one blob, not split into the USA version's files yet
  - name: stcrdshp
    type: databin
    start: 0x0
    vram: 0x80082CB0
    subalign: 4

  - [0xA250]
