# Digimon World 2003, Europe (SLES-03936): stdgname
name: stdgname
sha1: ae175dd74fd855e08cfdf0bec9d03f473f02d25a
options:
  basename: stdgname
  target_path: disks/eu/AAA/PRO/STDGNAME.PRO
  base_path: ../..
  platform: psx
  compiler: GCC

  asm_path: asm/eu/stdgname
  src_path: src/stdgname
  build_path: build/eu

  ld_script_path: build/eu/generated/stdgname.ld

  global_vram_start: 0x80000000
  global_vram_end: 0x80200000

  find_file_boundaries: True
  gp_value: 0x8005CB50

  generate_asm_macros_files: False

  section_order: [".rodata", ".text", ".data", ".bss"]

  symbol_addrs_path:
    - config/eu/symbols.txt

  undefined_funcs_auto_path: build/eu/generated/undefined_funcs_auto_stdgname.txt
  undefined_syms_auto_path: build/eu/generated/undefined_syms_auto_stdgname.txt

  string_encoding: ASCII
  data_string_encoding: ASCII
  rodata_string_guesser_level: 2
  data_string_guesser_level: 2

  ld_bss_is_noload: False

  migrate_rodata_to_functions: True
  create_data_pads: False

segments:
  # not split into the USA version's files yet: its rodata, code and data
  - name: stdgname
    type: code
    start: 0x0
    vram: 0x80082CB0
    align: 4
    subalign: 4
    subsegments:
      - [0x0, rodata, stdgname]
      - [0x2DC, asm, stdgname]
      - [0x3B80, data, stdgname]
  - [0x6190]
