# Digimon World 2003, Europe (SLES-03936): stplnmet
name: stplnmet
sha1: 033c688b39835931ff0231a94363ceb5b4031ee1
options:
  basename: stplnmet
  target_path: disks/eu/AAA/PRO/STPLNMET.PRO
  base_path: ../..
  platform: psx
  compiler: GCC

  asm_path: asm/eu/stplnmet
  src_path: src/stplnmet
  build_path: build/eu

  ld_script_path: build/eu/generated/stplnmet.ld

  global_vram_start: 0x80000000
  global_vram_end: 0x80200000

  find_file_boundaries: True
  gp_value: 0x8005CB50

  generate_asm_macros_files: False

  section_order: [".rodata", ".text", ".data", ".bss"]

  symbol_addrs_path:
    - config/eu/symbols.txt

  undefined_funcs_auto_path: build/eu/generated/undefined_funcs_auto_stplnmet.txt
  undefined_syms_auto_path: build/eu/generated/undefined_syms_auto_stplnmet.txt

  string_encoding: ASCII
  data_string_encoding: ASCII
  rodata_string_guesser_level: 2
  data_string_guesser_level: 2

  ld_bss_is_noload: False

  migrate_rodata_to_functions: True
  create_data_pads: False

segments:
  - name: stplnmet
    type: code
    start: 0x0
    vram: 0x80082CB0
    align: 4
    subalign: 4
    subsegments:
      # us's modules, each with its rodata, data and bss (tools/split_version.py)
      - [0x0, rodata, stplnmet]
      - [0x2A8, asm, stplnmet]
      - [0x5934, data, stplnmet]
  - [0x6F0C]
