name: fieldstg
sha1: 1168fd67a6fed16e7a084ee67449af9b8f216b8c
options:
  basename: fieldstg
  target_path: disks/us/AAA/PRO/FIELDSTG.PRO
  base_path: ..
  platform: psx
  compiler: GCC

  asm_path: asm/fieldstg
  src_path: src/fieldstg
  build_path: build

  ld_script_path: build/generated/fieldstg.ld

  global_vram_start: 0x80000000
  global_vram_end: 0x80200000

  find_file_boundaries: True
  gp_value: 0x8005C2F8

  generate_asm_macros_files: False

  section_order: [".rodata", ".text", ".data", ".bss"]

  symbol_addrs_path:
    - config/symbols.txt
    - config/symbols_fieldstg.txt

  undefined_funcs_auto_path: build/generated/undefined_funcs_auto_fieldstg.txt
  undefined_syms_auto_path: build/generated/undefined_syms_auto_fieldstg.txt

  string_encoding: ASCII
  data_string_encoding: ASCII
  rodata_string_guesser_level: 2
  data_string_guesser_level: 2

  ld_bss_is_noload: False

  migrate_rodata_to_functions: True
  create_data_pads: False

segments:
  - name: fieldstg
    type: code
    start: 0x0
    vram: 0x80082448
    align: 4
    subalign: 4
    subsegments:
      - [0x0, .rodata, fieldstg]
      - [0xAD4, c, fieldstg]
      - [0xFC60, data, fieldstg]
  - [0x18748]
