name: stcrdshp
sha1: ce654008ec31da3179728f0894af0ffbf88da7e6
options:
  basename: stcrdshp
  target_path: disks/us/AAA/PRO/STCRDSHP.PRO
  base_path: ..
  platform: psx
  compiler: GCC

  asm_path: asm/stcrdshp
  src_path: src/stcrdshp
  build_path: build

  ld_script_path: build/generated/stcrdshp.ld

  global_vram_start: 0x80000000
  global_vram_end: 0x80200000

  find_file_boundaries: True
  gp_value: 0x8005C2F8

  generate_asm_macros_files: False

  section_order: [".rodata", ".text", ".data", ".bss"]

  symbol_addrs_path:
    - config/symbols.txt
    - config/symbols_stcrdshp.txt

  undefined_funcs_auto_path: build/generated/undefined_funcs_auto_stcrdshp.txt
  undefined_syms_auto_path: build/generated/undefined_syms_auto_stcrdshp.txt

  string_encoding: ASCII
  data_string_encoding: ASCII
  rodata_string_guesser_level: 2
  data_string_guesser_level: 2

  ld_bss_is_noload: False

  migrate_rodata_to_functions: True
  create_data_pads: False

segments:
  - name: stcrdshp
    type: code
    start: 0x0
    vram: 0x80082448
    align: 4
    subalign: 4
    subsegments:
      - [0x0, .rodata, stcrdshp]
      - [0x35C, c, stcrdshp]
      - [0x6480, .data, stcrdshp]
  - [0xA104]
