name: stcrddek
sha1: 04f46fb6aa7d83e0a0255c95fd2360ba138d0680
options:
  basename: stcrddek
  target_path: disks/us/AAA/PRO/STCRDDEK.PRO
  base_path: ..
  platform: psx
  compiler: GCC

  asm_path: asm/stcrddek
  src_path: src/stcrddek
  build_path: build

  ld_script_path: build/generated/stcrddek.ld

  global_vram_start: 0x80000000
  global_vram_end: 0x80200000

  find_file_boundaries: True
  gp_value: 0x8005C2F8

  generate_asm_macros_files: False

  section_order: [".rodata", ".text", ".data", ".bss"]

  symbol_addrs_path:
    - config/symbols.txt
    - config/symbols_stcrddek.txt

  undefined_funcs_auto_path: build/generated/undefined_funcs_auto_stcrddek.txt
  undefined_syms_auto_path: build/generated/undefined_syms_auto_stcrddek.txt

  string_encoding: ASCII
  data_string_encoding: ASCII
  rodata_string_guesser_level: 2
  data_string_guesser_level: 2

  ld_bss_is_noload: False

  migrate_rodata_to_functions: True
  create_data_pads: False

segments:
  - name: stcrddek
    type: code
    start: 0x0
    vram: 0x80082448
    align: 4
    subalign: 4
    subsegments:
      - [0x0, .rodata, stcrddek]
      - [0x540, c, stcrddek]
      - [0x74FC, .data, stcrddek]
  - [0x88CC]
