name: stgmcard
sha1: 321d0a1e14178b79f0dc94a426a7643b49a75ceb
options:
  basename: stgmcard
  target_path: disks/us/AAA/PRO/STGMCARD.PRO
  base_path: ..
  platform: psx
  compiler: GCC

  asm_path: asm/stgmcard
  src_path: src/stgmcard
  build_path: build

  ld_script_path: build/generated/stgmcard.ld

  global_vram_start: 0x80000000
  global_vram_end: 0x80200000

  find_file_boundaries: True
  gp_value: 0x8005C2F8

  generate_asm_macros_files: False

  section_order: [".rodata", ".text", ".data", ".bss"]

  symbol_addrs_path:
    - config/symbols.txt
    - config/symbols_stgmcard.txt

  undefined_funcs_auto_path: build/generated/undefined_funcs_auto_stgmcard.txt
  undefined_syms_auto_path: build/generated/undefined_syms_auto_stgmcard.txt

  string_encoding: ASCII
  data_string_encoding: ASCII
  rodata_string_guesser_level: 2
  data_string_guesser_level: 2

  ld_bss_is_noload: False

  migrate_rodata_to_functions: True
  create_data_pads: False

segments:
  - name: stgmcard
    type: code
    start: 0x0
    vram: 0x80082448
    align: 4
    subalign: 4
    subsegments:
      - [0x0, .rodata, stgmcard]
      - [0x20, c, stgmcard]
      - [0x5274, .data, stgmcard]
  - [0x5B3C]
