# Digimon World 3, USA (SLUS-01436): fightstg
name: fightstg
sha1: e0605a184bff15e3b25887033d593f9564aac286
options:
  basename: fightstg
  target_path: disks/us/AAA/PRO/FIGHTSTG.PRO
  base_path: ../..
  platform: psx
  compiler: GCC

  asm_path: asm/us/fightstg
  src_path: src/fightstg
  build_path: build/us

  ld_script_path: build/us/generated/fightstg.ld

  global_vram_start: 0x80000000
  global_vram_end: 0x80200000

  find_file_boundaries: True
  gp_value: 0x8005C2F8

  generate_asm_macros_files: False

  section_order: [".rodata", ".text", ".data", ".bss"]

  symbol_addrs_path:
    - config/us/symbols.txt
    - config/us/symbols_fightstg.txt

  undefined_funcs_auto_path: build/us/generated/undefined_funcs_auto_fightstg.txt
  undefined_syms_auto_path: build/us/generated/undefined_syms_auto_fightstg.txt

  string_encoding: ASCII
  data_string_encoding: ASCII
  rodata_string_guesser_level: 2
  data_string_guesser_level: 2

  ld_bss_is_noload: False

  migrate_rodata_to_functions: True
  create_data_pads: False

segments:
  - name: fightstg
    type: code
    start: 0x0
    vram: 0x80082448
    align: 4
    subalign: 4
    subsegments:
      - [0x0, .rodata, fightstg]
      - [0x1C, .rodata, fightstg_2]
      - [0x38, .rodata, fightstg_3]
      - [0x16C, .rodata, fightstg_4]
      - [0x188, .rodata, fightstg_5]
      - [0x234, .rodata, fightstg_6]
      - [0x608, c, fightstg]
      - [0x352C, c, fightstg_2]
      - [0x3D38, c, fightstg_3]
      - [0x7E28, c, fightstg_4]
      - [0x8968, c, fightstg_5]
      - [0xA4A8, c, fightstg_6]
      - [0x1EC00, c, fightstg_7]
      - [0x1EDF0, .data, fightstg]
  - [0x210B8]
