# Digimon World 3, USA (SLUS-01436): soundtst
name: soundtst
sha1: a98ad009db0c0c15b210755c2cb108e6e3e1a0dd
options:
  basename: soundtst
  target_path: disks/us/AAA/PRO/SOUNDTST.PRO
  base_path: ../..
  platform: psx
  compiler: GCC

  asm_path: asm/us/soundtst
  src_path: src/soundtst
  build_path: build/us

  ld_script_path: build/us/generated/soundtst.ld

  global_vram_start: 0x80000000
  global_vram_end: 0x80200000

  find_file_boundaries: True
  gp_value: 0x8005C2F8

  generate_asm_macros_files: False

  section_order: [".rodata", ".text", ".data", ".bss"]

  symbol_addrs_path:
    - config/us/symbols.txt
    - config/us/symbols_soundtst.txt

  undefined_funcs_auto_path: build/us/generated/undefined_funcs_auto_soundtst.txt
  undefined_syms_auto_path: build/us/generated/undefined_syms_auto_soundtst.txt

  string_encoding: ASCII
  data_string_encoding: ASCII
  rodata_string_guesser_level: 2
  data_string_guesser_level: 2

  ld_bss_is_noload: False

  migrate_rodata_to_functions: True
  create_data_pads: False

segments:
  - name: soundtst
    type: code
    start: 0x0
    vram: 0x80082448
    align: 4
    subalign: 4
    subsegments:
      - [0x0, .rodata, soundtst]
      - [0x16C0, c, soundtst]
      - [0x20C4, .data, soundtst]
  - [0x2D98]
