# Digimon World 3, USA (SLUS-01436): stdgname
name: stdgname
sha1: 1d52a5bc5bb82b825b48457954e7245328da46bf
options:
  basename: stdgname
  target_path: disks/us/AAA/PRO/STDGNAME.PRO
  base_path: ../..
  platform: psx
  compiler: GCC

  asm_path: asm/us/stdgname
  src_path: src/stdgname
  build_path: build/us

  ld_script_path: build/us/generated/stdgname.ld

  global_vram_start: 0x80000000
  global_vram_end: 0x80200000

  find_file_boundaries: True
  gp_value: 0x8005C2F8

  generate_asm_macros_files: False

  section_order: [".rodata", ".text", ".data", ".bss"]

  symbol_addrs_path:
    - config/us/symbols.txt
    - config/us/symbols_stdgname.txt

  undefined_funcs_auto_path: build/us/generated/undefined_funcs_auto_stdgname.txt
  undefined_syms_auto_path: build/us/generated/undefined_syms_auto_stdgname.txt

  string_encoding: ASCII
  data_string_encoding: ASCII
  rodata_string_guesser_level: 2
  data_string_guesser_level: 2

  ld_bss_is_noload: False

  migrate_rodata_to_functions: True
  create_data_pads: False

segments:
  - name: stdgname
    type: code
    start: 0x0
    vram: 0x80082448
    align: 4
    subalign: 4
    subsegments:
      - [0x0, .rodata, stdgname]
      - [0x2C4, .rodata, stdgname_2]
      - [0x2DC, c, stdgname]
      - [0x32AC, c, stdgname_2]
      - [0x3930, .data, stdgname]
  - [0x5F40]
