# Digimon World 3, USA (SLUS-01436): stitshop
name: stitshop
sha1: a7ef0031107436bf7c31f8a9b2518128f653aa22
options:
  basename: stitshop
  target_path: disks/us/AAA/PRO/STITSHOP.PRO
  base_path: ../..
  platform: psx
  compiler: GCC

  asm_path: asm/us/stitshop
  src_path: src/stitshop
  build_path: build/us

  ld_script_path: build/us/generated/stitshop.ld

  global_vram_start: 0x80000000
  global_vram_end: 0x80200000

  find_file_boundaries: True
  gp_value: 0x8005C2F8

  generate_asm_macros_files: False

  section_order: [".rodata", ".text", ".data", ".bss"]

  symbol_addrs_path:
    - config/us/symbols.txt
    - config/us/symbols_stitshop.txt

  undefined_funcs_auto_path: build/us/generated/undefined_funcs_auto_stitshop.txt
  undefined_syms_auto_path: build/us/generated/undefined_syms_auto_stitshop.txt

  string_encoding: ASCII
  data_string_encoding: ASCII
  rodata_string_guesser_level: 2
  data_string_guesser_level: 2

  ld_bss_is_noload: False

  migrate_rodata_to_functions: True
  create_data_pads: False

segments:
  - name: stitshop
    type: code
    start: 0x0
    vram: 0x80082448
    align: 4
    subalign: 4
    subsegments:
      - [0x0, .rodata, stitshop]
      - [0x56C, c, stitshop]
      - [0x9C8C, .data, stitshop]
  - [0xA3BC]
