# Digimon World 3, USA (SLUS-01436): wfightts
name: wfightts
sha1: e8fe8a3c9f45077c64ad89a1cee95e6045ef7af1
options:
  basename: wfightts
  target_path: disks/us/AAA/PRO/WFIGHTTS.PRO
  base_path: ../..
  platform: psx
  compiler: GCC

  asm_path: asm/us/wfightts
  src_path: src/wfightts
  build_path: build/us

  ld_script_path: build/us/generated/wfightts.ld

  global_vram_start: 0x80000000
  global_vram_end: 0x80200000

  find_file_boundaries: True
  gp_value: 0x8005C2F8

  generate_asm_macros_files: False

  section_order: [".rodata", ".text", ".data", ".bss"]

  symbol_addrs_path:
    - config/us/symbols.txt
    - config/us/symbols_wfightts.txt

  undefined_funcs_auto_path: build/us/generated/undefined_funcs_auto_wfightts.txt
  undefined_syms_auto_path: build/us/generated/undefined_syms_auto_wfightts.txt

  string_encoding: ASCII
  data_string_encoding: ASCII
  rodata_string_guesser_level: 2
  data_string_guesser_level: 2

  ld_bss_is_noload: False

  migrate_rodata_to_functions: True
  create_data_pads: False

segments:
  - name: wfightts
    type: code
    start: 0x0
    vram: 0x800A4CA4
    align: 4
    subalign: 4
    subsegments:
      - [0x0, .rodata, wfightts]
      - [0x9D8, c, wfightts]
      - [0x3578, .data, wfightts]
  - [0x38FC]
